#!/usr/bin/env python3
"""Generate the responsive WebP variants of every project image and the
intrinsic-size table used by the site. Safe to re-run.

  thumbs/sm/<name>.webp   480w   grids on phones
  thumbs/<name>.webp      960w   grids on tablets / desktop
  thumbs/xl/<name>.webp   1800w  lightbox
  <Project>-thumbnail-836.webp / -1672.webp   16:9 covers
  src/data/imageSizes.ts  [width, height] of every original

Usage:  python3 scripts/image-variants.py
"""
import glob
import json
import os

from PIL import Image

ROOT = "public/images/projects"
# Moderna originals are Instagram-frame mockups: grid previews show the post only
MODERNA_FRAME = ((1107, 1543), (61, 245, 1060, 1300))


def save(img, path, width, quality):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    c = img.copy()
    c.thumbnail((width, width), Image.LANCZOS)
    c.save(path, "WEBP", quality=quality, method=6)


sizes = {}
for f in sorted(glob.glob(ROOT + "/**/*", recursive=True)):
    if "/thumbs/" in f or not f.lower().endswith((".png", ".jpg", ".jpeg")):
        continue
    im = Image.open(f).convert("RGB")
    sizes[f[len("public"):]] = list(im.size)
    d, base = os.path.dirname(f), os.path.splitext(os.path.basename(f))[0]
    if "-thumbnail" in base:
        for w in (836, 1672):
            save(im, os.path.join(d, f"{base}-{w}.webp"), w, 82)
        continue
    preview = im.crop(MODERNA_FRAME[1]) if "/moderna/" in f and im.size == MODERNA_FRAME[0] else im
    save(preview, os.path.join(d, "thumbs", "sm", base + ".webp"), 480, 76)
    save(preview, os.path.join(d, "thumbs", base + ".webp"), 960, 78)
    save(im, os.path.join(d, "thumbs", "xl", base + ".webp"), 1800, 80)

lines = [
    "// Generated by scripts/image-variants.py: intrinsic [width, height] of every image,",
    "// used to reserve space (no layout shift) and to keep true aspect ratios in galleries.",
    "export const imageSizes: Record<string, [number, number]> = {",
]
lines += [f"  {json.dumps(k)}: [{w}, {h}]," for k, (w, h) in sizes.items()]
lines.append("};")
with open("src/data/imageSizes.ts", "w") as fh:
    fh.write("\n".join(lines) + "\n")
print(f"{len(sizes)} images processed")
